from enum import Enum

class FileClassification(str, Enum):
    INDEX = "INDEX"
    MAP = "MAP"
    LEGEND = "LEGEND"
    UPSTREAM_OUTPUT = "UPSTREAM_OUTPUT"
    REFERENCE = "REFERENCE"
    SAFETY_REFERENCE = "SAFETY_REFERENCE"
    OTHER = "OTHER"
    UNKNOWN = "UNKNOWN"

class DocumentResolutionStatus(str, Enum):
    UNIQUE = "UNIQUE"
    MISSING = "MISSING"
    AMBIGUOUS = "AMBIGUOUS"
    EXCLUDED = "EXCLUDED"
    INVALID = "INVALID"

class PDFModality(str, Enum):
    VECTOR = "VECTOR"
    RASTER = "RASTER"
    HYBRID = "HYBRID"
    UNREADABLE = "UNREADABLE"

class Severity(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    UNKNOWN = "UNKNOWN"

class GeometryType(str, Enum):
    LINE = "LINE"
    POLYGON = "POLYGON"
    POINT = "POINT"
    MULTI_LINE = "MULTI_LINE"
    BUFFERED_LINE = "BUFFERED_LINE"
    UNKNOWN = "UNKNOWN"

class AOIDetectionMethod(str, Enum):
    NATIVE_VECTOR = "NATIVE_VECTOR"
    EXPLICIT_GEOMETRY = "EXPLICIT_GEOMETRY"
    EXTERNAL_SOURCE = "EXTERNAL_SOURCE"
    CV_CONTOUR = "CV_CONTOUR"
    FALLBACK = "FALLBACK"

class DetectionMethod(str, Enum):
    VECTOR_ANALYSIS = "VECTOR_ANALYSIS"
    CLASSICAL_CV = "CLASSICAL_CV"
    OCR_EXTRACTION = "OCR_EXTRACTION"
    TEXT_LABEL = "TEXT_LABEL"
    HYBRID_FUSION = "HYBRID_FUSION"


class ReconciliationOutcome(str, Enum):
    MATCH = "MATCH"
    MISSED_WARNING = "MISSED_WARNING"
    POSSIBLE_FALSE_POSITIVE = "POSSIBLE_FALSE_POSITIVE"
    TYPE_MISMATCH = "TYPE_MISMATCH"
    LOCATION_MISMATCH = "LOCATION_MISMATCH"
    DUPLICATE = "DUPLICATE"
    CONFIRMED_CLEAN = "CONFIRMED_CLEAN"
    UNCERTAIN = "UNCERTAIN"

class Decision(str, Enum):
    AUTO_CLEAR = "AUTO_CLEAR"
    HUMAN_REVIEW = "HUMAN_REVIEW"
    BLOCKED = "BLOCKED"

class HumanDispositionAction(str, Enum):
    CONFIRM_WARNING = "CONFIRM_WARNING"
    REJECT_WARNING = "REJECT_WARNING"
    ADD_WARNING = "ADD_WARNING"
    REMOVE_WARNING = "REMOVE_WARNING"
    BLOCK = "BLOCK"
    REQUEST_SECOND_REVIEW = "REQUEST_SECOND_REVIEW"
