"""Initial schema for Phase 15 persistence

Revision ID: c56f8142889c
Revises: 
Create Date: 2026-09-02 20:00:57.896616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c56f8142889c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('job_id', sa.String(length=128), nullable=False),
    sa.Column('root_dir', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('total_documents', sa.Integer(), nullable=False),
    sa.Column('auto_clear_count', sa.Integer(), nullable=False),
    sa.Column('human_review_count', sa.Integer(), nullable=False),
    sa.Column('blocked_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index('ix_jobs_created_at', 'jobs', ['created_at'], unique=False)
    op.create_index('ix_jobs_status', 'jobs', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=128), nullable=False),
    sa.Column('document_id', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_document_id', 'audit_logs', ['document_id'], unique=False)
    op.create_index('ix_audit_logs_job_id', 'audit_logs', ['job_id'], unique=False)
    op.create_index('ix_audit_logs_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_table('documents',
    sa.Column('document_id', sa.String(length=128), nullable=False),
    sa.Column('job_id', sa.String(length=128), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=256), nullable=True),
    sa.Column('utility_type', sa.String(length=128), nullable=True),
    sa.Column('modality', sa.String(length=32), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('reconciliation_outcome', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index('ix_documents_decision', 'documents', ['decision'], unique=False)
    op.create_index('ix_documents_job_id', 'documents', ['job_id'], unique=False)
    op.create_table('evidence_items',
    sa.Column('evidence_id', sa.String(length=128), nullable=False),
    sa.Column('document_id', sa.String(length=128), nullable=False),
    sa.Column('page_num', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.Column('crop_image_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index('ix_evidence_document_id', 'evidence_items', ['document_id'], unique=False)
    op.create_table('human_dispositions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('reviewer_id', sa.String(length=128), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_human_dispositions_document_id', 'human_dispositions', ['document_id'], unique=False)
    op.create_table('policy_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=128), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('gates_json', sa.Text(), nullable=True),
    sa.Column('reconciliation_id', sa.String(length=128), nullable=True),
    sa.Column('evidence_package_id', sa.String(length=128), nullable=True),
    sa.Column('safe_mode_applied', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_policy_results_document_id', 'policy_results', ['document_id'], unique=False)
    op.create_table('reconciliations',
    sa.Column('reconciliation_id', sa.String(length=128), nullable=False),
    sa.Column('document_id', sa.String(length=128), nullable=False),
    sa.Column('outcome', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('claimed_warning_json', sa.Text(), nullable=True),
    sa.Column('detected_candidates_json', sa.Text(), nullable=True),
    sa.Column('evidence_ids_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.PrimaryKeyConstraint('reconciliation_id')
    )
    op.create_index('ix_reconciliations_document_id', 'reconciliations', ['document_id'], unique=False)
    op.create_index('ix_reconciliations_outcome', 'reconciliations', ['outcome'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reconciliations_outcome', table_name='reconciliations')
    op.drop_index('ix_reconciliations_document_id', table_name='reconciliations')
    op.drop_table('reconciliations')
    op.drop_index('ix_policy_results_document_id', table_name='policy_results')
    op.drop_table('policy_results')
    op.drop_index('ix_human_dispositions_document_id', table_name='human_dispositions')
    op.drop_table('human_dispositions')
    op.drop_index('ix_evidence_document_id', table_name='evidence_items')
    op.drop_table('evidence_items')
    op.drop_index('ix_documents_job_id', table_name='documents')
    op.drop_index('ix_documents_decision', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_audit_logs_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_logs_job_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_document_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_jobs_status', table_name='jobs')
    op.drop_index('ix_jobs_created_at', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
